### ISSUE TITLE
how to add arguments to the cached_data method

### ISSUE THREAD

**Issue by abbood** [deanishe/alfred-workflow#109]
I would like to cache methods that have arguments in them.. how can i do that with [wf.cached_data](http://www.deanishe.net/alfred-workflow/api/workflow.html?highlight=cached_data#workflow.workflow.Workflow.cached_data)? 

if i call it like so:
```
colNum, sheetTitle, projects, hours = wf.cached_data('projects_hours', get_projects_and_hours(service, spreadsheetId), max_age=60)
```

i get

```
 ERROR    'tuple' object is not callable
Traceback (most recent call last):
  File "/Users/abbood/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B0A73475-E69F-45F9-AC1D-36769C0627DF/workflow/workflow.py", line 2200, in run
    func(self)
  File "log_hours.py", line 167, in main
    colNum, sheetTitle, projects, hours = wf.cached_data('projects_hours', get_projects_and_hours(service, spreadsheetId), max_age=60)
  File "/Users/abbood/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B0A73475-E69F-45F9-AC1D-36769C0627DF/workflow/workflow.py", line 1833, in cached_data
    data = data_func()
TypeError: 'tuple' object is not callable
10:33:28 workflow.py:2231 DEBUG    Workflow finished in 3.624 seconds.
```

**Comment by idpaterson** [comment]
You will need to pass a function to `data_func` rather than the result of calling that function. So, if you want `get_projects_and_hours(service, spreadsheetId)` to provide the default value for cached data you could simply wrap it in a lambda that when called returns the result of that function with the specified arguments, like this:
```python
colNum, sheetTitle, projects, hours = wf.cached_data('projects_hours', lambda: get_projects_and_hours(service, spreadsheetId), max_age=60)
```

**Comment by deanishe** [comment]
To expand on what @idpaterson said, the whole point of `wf.cached_data()` is avoid making slow calls to retrieve data whenever possible. That is to say, its purpose is to *avoid* calling your `get_projects_and_hours()` function whenever possible.

Thus, you have to pass `cached_data()` the function itself (i.e. `my_func` *not* `my_func()`), so `cached_data()` can call it only if necessary. Passing in data defeats the entire purpose of `cached_data()` because that means you've already called `get_projects_and_hours()`.

If your new-data function needs arguments, wrap it with `lambda:`, as @idpaterson suggested, or if you don't like that, curry it with `functools.partial` or create a simple wrapper function, instead:

```python
# option 2: curry the data function
from functools import partial

colNum, sheetTitle, projects, hours = wf.cached_data('projects_hours', partial(get_projects_and_hours, service, spreadsheetId), max_age=60)
```

```python
# option 3: inline wrapper func
def _wrapper():
    return get_projects_and_hours(service, spreadsheetId)

colNum, sheetTitle, projects, hours = wf.cached_data('projects_hours', _wrapper, max_age=60)
```
