### ISSUE TITLE
wf.cached_data error when input /   !!!

### ISSUE THREAD

**Issue by ycjcl868** [deanishe/alfred-workflow#118]
When I input the text including `/` , the `wf.cached_data` function is error like this.

![image](https://user-images.githubusercontent.com/13595509/30959204-035a7744-a472-11e7-9f80-0a512f0e6dbe.png)

How do I deal with the bug?

**Comment by deanishe** [comment]
> How do I deal with the bug?

Don’t use names with slashes. 

The name is used for the filename of the cached file, so don’t use slashes or colons.

**Comment by ycjcl868** [comment]
But the content I will search includes the slashes ,

**Comment by ycjcl868** [comment]
I think it's a bug.

**Comment by deanishe** [comment]
> But the content I will search includes the slashes

The content is unaffected. You just can't use slashes in the cache name. Replace slashes with `--` or something like that.

> I think it's a bug.

It's not. It's a feature.

I can't possibly know what kind of cache keys users want to use. The only way I could safely prevent clashing filenames would be to hash the cache keys and use the hashes as filenames. This would mean:

1. You can't choose your own filenames for caches.
2. As a result of that, it becomes extremely difficult to [only delete certain cache files](https://github.com/deanishe/alfred-reddit/blob/4dfdb66a31baac8e22c95df7be16d003c20fe515/src/reddit.py#L312).
3. Debugging is harder because any obvious link between input and cache file is lost.

So I deliberately leave it up to the library's users, who understand their workflows' data and how they want to use the cache, to choose their own cache names.

Please look at [how](https://github.com/deanishe/alfred-reddit/blob/4dfdb66a31baac8e22c95df7be16d003c20fe515/src/reddit.py#L121) I [assign](https://github.com/deanishe/alfred-reddit/blob/4dfdb66a31baac8e22c95df7be16d003c20fe515/src/reddit.py#L396) cache [keys](https://github.com/deanishe/alfred-reddit/blob/4dfdb66a31baac8e22c95df7be16d003c20fe515/src/reddit.py#L430) and [clear the cache](https://github.com/deanishe/alfred-reddit/blob/4dfdb66a31baac8e22c95df7be16d003c20fe515/src/reddit.py#L312) in my [reddit workflow](https://github.com/deanishe/alfred-reddit) to see why.

If you don't care about any of that, just hash your queries to get a filesystem-safe cache key:

```python
import hashlib

def cache_key(query):
    return hashlib.md5(query.encode('utf-8')).hexdigest()

cache_key(u'a/b/c')
# -> 'cff49f359f080f71548fcee824af6ad3'
```

I will not change this behaviour. I understand perfectly well that it means a bit more work for workflow authors—I use the library an awful lot myself—but it places a much smaller burden on users who want to use slashes in cache keys than hashed keys would on users who want to selectively clear cache files.
