### ISSUE TITLE
Pass parameter to subprocess

### ISSUE THREAD

**Issue by AngelPone** [deanishe/alfred-workflow#144]
I tried to pass arguments to subprocess, but there was no result, and no debug output

```python
kwags = {'stdin': args.URL}
cmd = ['/usr/bin/python', wf.workflowfile('add_background.py')]
run_in_background('add', cmd, **kwags)
```

below is `add_background.py`
```
def main(wf):
    data = wf.stored_data('bookmarks')
    for line in sys.stdin:
        url = line.strip()
        wf.logger.debug('this is url: %s' % url)
        title, url = get_title(url)
        data.append({
            'title': title,
            'url': url
        })
    wf.store_data('bookmarks')
    wf.logger.debug('%s' % title)
```

Thanks for your help ! 🆘🆘🆘

**Comment by AngelPone** [comment]
I solved it ..

**Comment by MikeMajara** [comment]
> I solved it ..

Could you post how you solved it? Then whoever comes across the same problem can see a solution here.

**Comment by deanishe** [comment]
> Could you post how you solved it?

I don't think he solved it so much as figured out what's happening.

Background processes aren't connected to STDOUT/STDERR (otherwise Alfred would wait for them), so their log output doesn't appear in Alfred's debugger. It's only written to the log file.

**Comment by MikeMajara** [comment]
Ok, so that took me a while to figure out so I'll post how I did it:

As @deanishe says, background processes aren't connected to STDOUT/STDERR. So you can `cd` into your workflow directory and find your log file (also with [Workflow.logfile](http://www.deanishe.net/alfred-workflow/api/index.html#workflow.Workflow.logfile)). once in there just follow your file with `tail +1f com.Your.Workflow.Name.log`, that will give you a continuos output on all log written to file.

I could also log here the args that where getting passed to the background process and how. Which was my original issue.

**Comment by deanishe** [comment]
If you're workflow is set up to use [magic arguments](https://www.deanishe.net/alfred-workflow/guide/magic-arguments.html) (i.e. there's a Script Filter that uses `Workflow.args`), you can open the log file directly by entering the search query `workflow:openlog`.
