### ISSUE TITLE
Self-initializing workflow data

### ISSUE THREAD

**Issue by fractaledmind** [deanishe/alfred-workflow#42]
I've recently started thinking about how I could abstract a technique I've started using in my most recent re-write of ZotQuery and Pandoctor: self-initializing data accessible via object properties. Let me explain what I mean by that. Both ZotQuery and Pandoctor are Alfred GUIs for some other application or utility which generates and uses alot of non-volatile data. For example, with ZotQuery, I am pulling from a user's Zotero database data. In order to increase speed, I have written ZotQuery and Pandoctor in such a way as to get the data I need in the format I need, and then write it to disk in the workflow's non-volatile directory (from which all workflow functions then read accordingly). So, this data is non-volatile, essential, and not settings. Also, the workflow will need this data _all of the time_.  So, what of "self-initializing data"? My current approach is to get this data with the same consistent API each time, regardless of whether or not it exists. I do this by creating an Object Class with some introspection. Here's some of my ZotQuery code as an example:

```
class Zotero(object):
    """Contains all relevant information about user's Zotero installation.

    :param wf: a new :class:`Workflow` instance.
    :type wf: :class:`object`

    """
    def __init__(self, wf):
        self.wf = wf
        self.me = self.paths()

    def paths(self):
        """Dictionary of paths to relevant Zotero data:
            ==================      ============================================
            Key                     Description
            ==================      ============================================
            `original_sqlite`       Zotero's internal sqlite database
            `internal_storage`      Zotero's internal storage directory
            `external_storage`      Zotero's external directory for attachments

        Expects information to be stored in :file:`zotero_paths.json`.
        If file does not exist, it creates and stores dictionary.

        :returns: key Zotero paths
        :rtype: :class:`dict`

        """
        zotero_paths = self.wf.stored_data('zotero_paths')
        if zotero_paths == None:
            paths = {
                'original_sqlite': self.original_sqlite,
                'internal_storage': self.internal_storage,
                'external_storage': self.external_storage
            }
            self.wf.store_data('zotero_paths', paths,
                                    serializer='json')
            zotero_paths = paths
        return zotero_paths

    @property
    def original_sqlite(self):
        """Return path to Zotero's internal sqlite database.

        Expects information in :file:`zotero_paths.json`.
        If file doesn't exist, it finds path manually.

        :returns: full path to file
        :rtype: :class:`unicode`

        """
        try:
            return self.me['original_sqlite']
        except AttributeError:
            sqlites = self.find_name('zotero.sqlite')
            return sqlites[0] if sqlites != [] else None
```

The basic set-up is this: on initialization, run the `paths()` method and set the `me` attribute to the dictionary data returned. When `paths()` runs, it checks to see if the dictionary has been written to disk. If not, it generates the dictionary, writes it to disk, and then returns the dictionary (to be set to `self.me`). In generating the dictionary, it calls to object properties (like `original_sqlite`). These properties attempt to read the value from the dictionary (so that you can later access the property directly at read speed), but on first run this will raise an `AttributeError`, since the `self.me` variable isn't set yet. In this part of the code, you put whatever code you need in order to get the data required. In the example above, I use a wrapper for `mdfind` to find the full path to the user's Zotero sqlite database. The result is that I have all of the data I need access to initialized and written to disk on the first run, simply by creating an instance of the class. The idea here is basically the same of the idea behind the Alfred Bundler: have a consistent API where things are automatically fetched on first run and then read on all subsequent runs, although the API doesn't need to be aware of which run you are on. 

I think alot of workflows have some data of this sort, and if we could abstract this to provide an API for this, that could be very helpful. My problem is that I'm not certain how exactly one would do this (if it's even possible). Generically, I'm thinking of dynamically populating a sub-class of Workflow (akin to `Settings`) with properties, and the class is structured in this way. Is there a property generating decorator?

Anyways, is this feasible or even desirable in your mind?

**Comment by smargh** [comment]
In working on another project, I came back upon the need for this functionality, but didn't like my old implementation. Having a base class and a decorator is too much work and too finicky to implement. I also think the API should be more narrow in functionality. 

As I see it, the primary use case is to persist the data returned by a function/method that the workflow author deems to be generally non-volatile (by this I mean, the data is unlikely to change if the function/method were run again) and/or time-intensive to generate (by this I mean, the function/method takes a non-trivial amount of time to run). Obviously, any data that is both time-intensive to generate and generally non-volatile would be helped by persistence.

I propose, at least at first, a very simple API to handle only this scenario (that is, not a full-fledged smart data model). It is comprised of two functions: `@persist` and `refresh()` (the naming might not be perfect, I've considered `@persist`, `@persistent`, `@cache`, and `@cached` for the decorator name; `refresh()`, `reset()`, and `reload()` for the function name). 

You simply decorate a method or a function with the `@persist` decorator and it uses `Workflow.cached_data()` under the covers to cache the data if it doesn't exist, or read read the data if it does:
```
def persist(func):
    @functools.wraps(func)
    def func_wrapper(*args, **kwargs):
        # Get dictionary of args and kwargs
        args_map = inspect.getcallargs(func, *args, **kwargs) if args or kwargs else {}
        # If `self` one of the args, `func` is a bound method
        if 'self' in args_map:
            class_name = args_map['self'].__class__.__name__
        # Else, `func` is simply an unbound function
        else:
            class_name = ''
        func_name = func.__name__
        cache_name = ':'.join([class_name, func_name])
        return WF.cached_data(cache_name,
                              lambda: func(*args, **kwargs),
                              max_age=0)
    return func_wrapper
```

So, on first run, the function/method is run and the return value is saved to a cache file. On any subsequent run, the value is simply read from the cache value and returned.

If the workflow author wants, at any point to force the function/method to re-run (that is, regenerate the data and not read the old data from the cache), he can use the `refresh()` function.
```
def refresh(func, *args, **kwargs):
    try:
        class_name = func.__self__.__class__.__name__
    except AttributeError:
        class_name = ''
    meth_name = func.__name__
    cache_name = ':'.join([class_name, meth_name])
    WF.clear_cache(lambda f: cache_name in f)
    return func(*args, **kwargs)
```
This simply deletes the old cache file and reruns the function (thus creating a new cache file with the returned value).

Thoughts? To specific to be helpful in the library? Don't like the implementation? Don't see it as generally helpful?

**Comment by deanishe** [comment]
I don't really understand what advantage this has over `wf.cached_data()` and `wf.cache_data(data=None)`.

I see a couple of minor issues with the implementation:

1. It's better not to use `:` in the filenames, as colon is the classic Mac path separator. A colon will be shown as `:` in a shell, but as `/` in Finder. It shouldn't cause any issues, but can be confusing.
2. Your implementation relies on they're being a global `Workflow` instance named `WF`. If it needs a `Workflow` instance, it'd probably be safer implemented as methods on the `Workflow` class. That would seriously restrict its usefulness, however.

It might be worth considering for v2 (where the caching API won't be tied to a `Workflow` instance) as an alternative for `wf.cached_data()` etc., but the decorator would have to support a `max_age` argument.

FWIW, this technique is often called "memoization".

**Comment by smargh** [comment]
The primary advantage, to my mind, is code readability. I have so many properties in classes that serve as the information backend for a workflow that rarely change, but require a good bit of computing (whether that be measured by computing time or lines of code). If the logic requires numerous lines of code, in order to use the simply `wf.cached_data()` design, I would have something like this:
```
@property
def first_property()
    def wrapper():
        if some_conditional:
            do some logic
        elif other_conditional:
            do other logic
        else
            do default logic

    return wf.cached_data('first_property', wrapper, max_age=0)
```

My thinking was to make the property method itself the "wrapper" and use the decorator to reduce complexity and actually increase semantic clarity (e.g. saying this property or function should be "persisted" is shorter and clearer than writing an internal wrapper function and passing that to `wf.cached_data()`).

Other points:

* The delimiter can be anything.
* It would certainly be more useful in V2 when `cached_data()` is no longer tied to a `Workflow` instance, I agree.

**Comment by deanishe** [comment]
In that case, I guess it would save a few lines of code per property.

Obviously, the delimiter can be anything. I was just pointing out that colon is a bad choice.

As noted, I don't think there's a place for it in v1 of Alfred-Workflow due its needing a global `Workflow` instance with a specific name. Too brittle, imo.

Having a `@cached` decorator that takes optional `max_age` and `name` arguments might be interesting for v2, however.

**Comment by smargh** [comment]
Will keep in mind for v2 then.

**Comment by deanishe** [comment]
The more I think about it, the more I like the idea of a `@cached` decorator.

The default cache name would have to be wisely chosen to prevent clashes if a user calls every data retrieval function `get_data()`. Probably based on filepaths, as I think `module.func_name` won't work, as the current script is always called `__main__`.

**Comment by smargh** [comment]
We could simply use the function name, filename, and line number to create the cache name. Inside of a decorator, you can get this info via the `inspect` module with attributes like this:
```
func.func_code.co_firstlineno
func.func_code.co_filename
# could get just filename via os.path.basename(func.func_code.co_filename)
func.func_code.co_name
```

So, we could do something like `<file>.<function>.<line #>` as the cache name. This would ensure unique names for all functions.

I would then re-recommend having some function like `refresh()` that takes the function object and deletes the old cache before re-running the decorated function.

One trick I've discovered in playing around with this though, is that any `refresh()` like function that accepts a decorated function has to do a little bit of work to get the correct line number. If you were to `print(func.func_code.co_firstlineno)` from inside `refresh()`, you would get the line number of the wrapper inside the decorator. In order to get the line-number of the function, you need to use `next(c.cell_contents.func_code.co_firstlineno for c in func.func_closure)`. You need to use an analogous call to get function name and file name. However, you can get all of that information and it will match.

**Comment by smargh** [comment]
Here's my old sample code rewritten using this new methodology:
```
#!/usr/bin/python
# encoding: utf-8
from os.path import basename
import time
import functools
from workflow import Workflow


def refresh(func, *args, **kwargs):
    decorated_func = next(c.cell_contents.func_code
                          for c in func.func_closure)
    file_name = basename(decorated_func.co_filename).replace('.py', '')
    func_name = decorated_func.co_name
    line_num = str(decorated_func.co_firstlineno)
    cache_name = '.'.join([file_name, func_name, line_num])
    WF.clear_cache(lambda f: cache_name in f)
    return func(*args, **kwargs)


def persist(func):
    @functools.wraps(func)
    def func_wrapper(*args, **kwargs):
        file_name = basename(func.func_code.co_filename).replace('.py', '')
        func_name = func.func_code.co_name
        line_num = str(func.func_code.co_firstlineno)
        cache_name = '.'.join([file_name, func_name, line_num])
        return WF.cached_data(cache_name,
                              lambda: func(*args, **kwargs),
                              max_age=0)
    return func_wrapper


class MyClass(object):
    def __init__(self):
        pass

    @persist
    def first_property(self):
        # some code to get data
        return 'this is my first property'

    @persist
    def second_property(self):
        time.sleep(2)
        return 'this is my second property'


@persist
def f1():
    time.sleep(2)
    return 'this is a simple function'


@persist
def f2(x):
    time.sleep(2)
    return 'this is another function. It takes a param: {}'.format(x)


if __name__ == '__main__':
    WF = Workflow()
    m = MyClass()
    print(m.second_property())
    print(refresh(m.second_property))
    print(f2('hello'))
    print(refresh(f2, 'world'))
```

One thing I've realized is that using the line number will break things, obviously, if the line number changes. This is a problem. We probably shouldn't use the line number. So, the question is, how do we distinguish between functions of the same name?

**Comment by deanishe** [comment]
Came here to say "no line numbers", so yeah.

If you use filepath.classname.methodname or filepath.funcname, they must be unique.

The `refresh()` function is pushing quite hard on my "too much magic" limit, truth be told. I think I'd prefer to require named caches for that.

Perhaps if you used a more straightforward option and just added a `_cache_name` attribute to the decorated function, the code would be much less hairy.

**Comment by deanishe** [comment]
Also, looking at the code above, it doesn't really fit. I mean, you've decorated a property, which appears to mean it now needs to be called. Is there no way for it to continue to work like a property?

**Comment by smargh** [comment]
Yeah, that sample code was written back when I was only wanting to decorate properties. I have since broadened the scope, so I should go and rename those. 

I confess to not fully following your logic here:
>Perhaps if you used a more straightforward option and just added a `_cache_name` attribute to the decorated function, the code would be much less hairy.

**Comment by deanishe** [comment]
The first decorator (@persist or @cached or whatever) can attach the cache name to the function when it wraps it. There's then no need for any subsequent functions to try to figure out the cache name, as it's stored in an attribute of the function passed to it.

**Comment by smargh** [comment]
Wow. That actually kinda blew my mind. Once I thought about it for a second, it made total sense, but I've never thought of functions having attributes. That's kinda awesome.

The problem, in this scenario, is that I can't quite see how to set the `_cache_name` attribute when the function is a bound method. Let me explain, as far as I've been able to gather, getting the name of the class for a method within a decorator on that method is quite hard; primarily because that method has not been bound to the class yet, at the moment the decorator does its thing. The one solution I have found is to use `inspect.getcallargs(func, *args, **kwargs)` (I found this methodology on [this blog post](https://andrewbrookins.com/tech/how-to-get-the-name-of-the-class-of-a-decorated-method-in-python/)). This will grant you access to the `self` parameter of a method, from which you can get the class name. So, to focus on this issue directly, you would need a decorator like this:
```
def cached(name=None):
    def decorator(func):
        file_name = basename(func.func_code.co_filename).replace('.py', '')
        func_name = func.__name__
        def wrapper(*args, **kwargs):
            args_map = inspect.getcallargs(func, *args, **kwargs) or {}
            class_name = args_map['self'].__class__.__name__
            cache_name = '.'.join([file_name, class_name, func_name])
            # if user passed in a cache name, use that no matter what
            if name:
                cache_name = name
            return WF.cached_data(cache_name,
                                  lambda: func(*args, **kwargs),
                                  max_age=0)
        return wrapper
    return decorator
```

You have to be inside the `wrapper` to have access to the `*args` and `**kwargs` needed for `inspect.getcallargs()`. Now, the problem with setting an attribute on the function is that you need to set the attribute on the `wrapper()` function, since this is replacing the wrapped function (Martijn Pieters' [SO answer](http://stackoverflow.com/a/15794454) was quite clarifying to me on this point). But, how does the `decorator()` get access to the `wrapper()`s `cache_name` var? In order to set the attribute, you would need to have `wrapper._cache_name = cache_name` right before `return wrapper`, but at that point, `cache_name` is undefined. 

So, either you know more and can solve this, or we need to drop the class name from the `_cache_name` generating logic (would this allow for name collisions?)

**Comment by deanishe** [comment]
What about [a class-based decorator](https://github.com/deanishe/alfred-workflow/blob/master/workflow/workflow.py#L822)? You can use instance variables to store cache_name.

Alternatively, use a non-local variable via the dict trick (you can alter non-local vars, just not assign them):

```python
def decorator(func):
    vars = {}
    def wrapper(*args, **kwargs):
        vars['cache_name'] = …
        …
    wrapper.cache_name = vars['cache_name']
    return wrapper
```

To be perfectly honest, I think I'd still prefer a decorator that requires an explicit name. Much less magical, and if anything goes wrong, it's the user's fault :wink:

**Comment by deanishe** [comment]
Also FWIW, if you're after caching a whole buttload of data, it might be smarter to have specific data classes and use a metaclass to take care of the caching. That's how most ORMs do their thing, and I sense you like magic.

**Comment by smargh** [comment]
Well, I'm all for stronger param enforcement. In fact, it might be a little prone to user-breaking if we only have one param (`name`) and it's optional, because using the decorator like this:
```
@cached
def function():
    pass
```
will result in some `AttributeError` somewhere along the stack, since you would need to call the decorator, even without the optional `name` param, as `@cached()`.

Plus, that requiring the `name` param more closely mirrors the `cached_data()` functionality that this is essentially wrapping. 

Also, I strive for a nice balance of clarity and magic. I've just read too many fantasy books, so I tend toward the magic end of that balancing act :)

**Comment by smargh** [comment]
Would this work as the decorator then?
```
def cached(name):
    def decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            return WF.cached_data(name,
                                  lambda: func(*args, **kwargs),
                                  max_age=0)
        wrapper._cache_name = name
        return wrapper
    return decorator
```

**Comment by deanishe** [comment]
`max_age` has to be an option, or it's a functional regression vs v1.

To be honest, I'd prefer a `clear(cache_name)` to `refresh()`. It's more flexible (you can clear a cache without also updating it). This already exists with `wf.cache_data(cache_name, None)`, however.

Calling `refresh(func)` just looks weird to me. Maybe it's the name.

**Comment by smargh** [comment]
Ok. So if you want to re-generate any data via function/method, you simply do 
```
clear(cache_name)
function()
```
with the explicit two-liner? 

I can get down with that.

So that would be:
```
def clear(cache_name):
    WF.clear_cache(lambda f: cache_name in f)
```

**Comment by smargh** [comment]
Should we change the decorator name to `@cached_as(cache_name)` to make it more explicit?

**Comment by deanishe** [comment]
Theoretically, it would be `wf.cache_data(name, None)` to clear one specific cache, but we're talking about v2 and the caching API isn't done yet (I'm stuck on the implementation of the serialisers, which has to come first).

I think `@cached('blah')` is clear enough. I would associate `*_as()` with conversion, personally.

BTW, have you tried out the Dash docset for AW? The docs are going to need a new theme to work properly with Dash, but I think a Dash docset would be a cool thing to have.

**Comment by smargh** [comment]
I actually just redownloaded Dash on my new work computer two days ago, and got AW docs in there yesterday. You are right tho, having a Dash docset is great. I'm starting to get more consistent with heading there first, tho my old SO habits do die hard. I like the new logo BTW. Didn't notice when it was added, but I like it. Tho in Dash, given its smaller size, it looks more like a WWI helmet than a butler's hat.

**Comment by deanishe** [comment]
Also, would a corresponding `@stored(name, format=?)` be necessary? I suppose it should, all things considered.

Perhaps the two could be combined by having a `volatile=False` option. Though "volatile" has always struck me as not particularly descriptive.

**Comment by smargh** [comment]
Since it would be trivial to implement, and some asshole like me is bound to come demanding it :wink:, it's probably worth putting `@stored(name, format)` in v2. I think keeping them separate is probably best: 

1. It mirrors the current API, which most workflow authors will probably already be familiar with
2. `@cached()` doesn't allow for changing the serializer via param, like `@stored()` does.

**Comment by deanishe** [comment]
And after 30 seconds' more thought, sod it.

`@cached()` should just be a convenience for the simplest cases. It'd be no use, for example, for caching data from the same function under different names.

**Comment by deanishe** [comment]
Demanding people like you will just have to write their own wrapper functions :wink:

**Comment by smargh** [comment]
:+1:

**Comment by deanishe** [comment]
> I like the new logo BTW. Didn't notice when it was added, but I like it. Tho in Dash, given its smaller size, it looks more like a WWI helmet than a butler's hat.

I added the logo while trying to build a Dash docset. It definitely doesn't look so good in Dash, but it's the best I can do. I tried a bunch of things, and this looked the least bad in Dash.

My normal strategy with icons is to hope that Jono takes a shine to the workflow and whips up his own icon for it, and then sends it to me, the talented bastard.
