### ISSUE TITLE
14:04:22 workflow.py:2152 WARNING  Can't save last version: workflow has no version

### ISSUE THREAD

**Issue by stonefury** [deanishe/alfred-workflow#64]
Any clue why I'm getting this in my debug output?

14:04:22 workflow.py:2152 WARNING  Can't save last version: workflow has no version

**Comment by deanishe** [comment]
It's because your workflow has not specified a version number in a way Alfred-Workflow understands.

This is explained [in the documentation](http://www.deanishe.net/alfred-workflow/user-manual/versioning.html), which I would encourage you to consult before posting an issue.

The bottom line is, it doesn't really matter. You *must* specify a version number if you wish to enable self-updating, but it's otherwise not required.

That said, if you distribute your workflow to other people, it's a *very* good idea to use version numbers. It makes debugging user issues easier, as it's easy to check if they're using the latest version (AW logs the version for you) and not complaining about some ancient version of your workflow..

The specific warning you're getting about saving the last version is irrelevant if you don't use version numbers.

If you do, AW saves the last run version to make it easier for you to migrate any settings to a new version.

**Comment by stonefury** [comment]
@deanishe Sry. Thank you very much.

**Comment by deanishe** [comment]
No need to apologise. (Was my post rude?)

If the documentation is unclear at any point, or you  have a different problem with Alfred Workflow, please let me know ASAP.

**Comment by fengxuway** [comment]
> It's because your workflow has not specified a version number in a way Alfred-Workflow understands.
> 
> This is explained in detail [in the documentation](http://www.deanishe.net/alfred-workflow/user-manual/versioning.html), which I would encourage you to consult before posting an issue.
> 
> The bottom line is, it doesn't really matter. You _must_ specify a version number if you wish to enable self-updating, but it's otherwise not required.
> 
> That said, if you distribute your workflow to other people, it's a _very_ good idea to use version numbers. It makes debugging user issues easier, as it's easy to check if they're using the latest version (AW logs the version for you) and not complaining about some ancient version of your workflow..
> 
> The specific warning you're getting about saving the last version is irrelevant if you don't use version numbers.
> 
> If you do, AW saves the last run version to make it easier for you to migrate any settings to a new version.

The mention of document link has not found, It returns 404. New link in: <http://www.deanishe.net/alfred-workflow/guide/versioning.html>

**Comment by deanishe** [comment]
Thanks, @fengxuway, I’ve updated my above post accordingly.
