### ISSUE TITLE
Qu: Most likely cause of self.raw being None?

### ISSUE THREAD

**Issue by smargh** [deanishe/alfred-workflow#68]
I'm trying to figure out why one of my users is getting this error when using my Pandoctor workflow:
```
 File "pandoctor.py", line 226, in _formats
    lines = req.text.splitlines()
File "/Users/j*******/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.60CECC29-7BBE-4EE5-B5FC-C222BEEEFC55/workflow/web.py", line 220, in text
    return self.content
  File "/Users/j********/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.60CECC29-7BBE-4EE5-B5FC-C222BEEEFC55/workflow/web.py", line 205, in content
    self._content = self.raw.read()
AttributeError: 'NoneType' object has no attribute 'read'
```

During configuration, Pandoctor grabs the HTML of the Pandoc homepage and uses the README to build an index of all of its many flags and arguments. This error occurs when trying to get the text of the webpage. The internet connection isn't down (I've tested this, you get an error when trying to make the connection), but `web.py` has `self.raw` being `None`. 

It works fine on my machine, so it must be some kind of environmental variable that I'm not thinking of, but I can't figure it out. I was wondering if you had any insight into what factors might cause `web.py` to return `None` for `self.raw` after a simple GET request?

**Comment by deanishe** [comment]
No idea. You're using a very old version of Alfred-Workflow.

Please update and ask again if the problem persists.

**Comment by deanishe** [comment]
I was playing with Pandoctor today.

The problem is because you're using `web.request()` instead of `web.get()` and didn't set `allow_redirects` to `True` (which is the default with `web.get()`, but not `web.request()`).

There's no reason to use `web.request()` directly (the `method` argument is actually ignored due to Python's silly built-in URL libraries). `web.get()` has more sensible defaults.

It would probably be much more sensible to include the list of supported formats in your workflow, or at least store them as a JSON file at a URL you control. Relying on parsing 3rd-party HTML when you don't really have to is introducing a potentially large problem into your code.

**Comment by smargh** [comment]
>It would probably be much more sensible to include the list of supported formats in your workflow, or at least store them as a JSON file at a URL you control. Relying on parsing 3rd-party HTML when you don't really have to is introducing a potentially large problem into your code.

The reason I originally went to the website README was that it was always the most up to date, given any potential updates to Pandoc. I didn't want to be responsible for keeping the workflow up-to-date if some format name changes or a new format is added. So, I will try the `web.get()` solution first, but if that proves flakey, I will hard code and manually update. 

Thanks for the catch.

**Comment by deanishe** [comment]
Then write a cron job on your own machine that parses the README, generates a JSON file and uploads it (if the parsing succeeds).

Grabbing the latest list of supported formats is not necessarily the best idea, anyway, as there's no guarantee the user has the latest version of Pandoc installed.

Is there no way to get a list of supported formats from the `pandoc` executable?

**Comment by smargh** [comment]
The reason I go to the website is that it contains both the CLI-used name and a longer description (e.g. "native (native Haskell), json (JSON version of native AST), markdown (pandoc’s extended markdown), markdown_strict (original unextended markdown)")

I use the descriptions in the UI.

**Comment by deanishe** [comment]
Then how about combining the two? A list of all possible formats in a JSON file filtered by the formats supported by the installed version of Pandoc.

The main thrust is, people don't consider HTML to be data and don't think twice about changing it. If you keep the HTML parsing at your end only, instead of breaking everyone's workflow, you'll only break your script.

**Comment by deanishe** [comment]
@smargh I've just seen [the corresponding issue](https://github.com/smargh/alfred_pandoctor/issues/1) in the pandoctor repo.

I'd appreciate it if, in future, you'd "page" me from the workflow issue rather than opening an AW issue, or at least reference the source issue when posting one here. There's a lot more context in there.

It's definitely a problem that `web.py` returns `None` if a redirect fails, but I'd never have known that was the underlying issue if I hadn't decided to use pandoctor myself and dug around in the source code.

**Comment by smargh** [comment]
Good point. I will reference you from the Pandoctor (or whatever the next workflow is where something comes up). Sorry for double posting.
