### ISSUE TITLE
How to store data in workflowdir ?

### ISSUE THREAD

**Issue by PierBover** [deanishe/alfred-workflow#72]
I know this is not a best practice, but I want to save data in the wokflowdir so I can have it shared on all my machines via dropbox.

I've seen that by default `store_data()` saves in the Library/application support/... directory but I'd lose the sync option.

Is there an easy way to do this with alfred-workflow or do I have to write myself?

**Comment by deanishe** [comment]
There is `Workflow.workflowfile('some_filename.ext')`, which will return the full path to `some_filename.ext` in the workflow directory.

But no, there are no APIs similar to `store_data()` or `cache_data()` for the workflow directory simply because, as you say, it's not best practice to do so.

If this is a workflow you plan on releasing (i.e. people may download and install a newer version at some date), I'd consider creating a separate directory *above* the workflow directory (i.e. a sibling directory). That way, you can still sync data between machines, but the data won't be overwritten if the workflow is re-installed/updated.

**Comment by PierBover** [comment]
Thanks, that's a great idea which I hadn't considered.

Do you think this could be useful for the main repo? I'm debating wether to fork and implement it in your repo, or put that logic in my workflow.

**Comment by deanishe** [comment]
> Do you think this could be useful for the main repo?

If there were demand for it. I've brought this up on the [Alfred forum](http://www.alfredforum.com) before, but the idea never gained traction…

The "proper" directory to use would probably be something like `../../sync/<bundleid>` relative to your workflow's directory (which would make `sync` a sibling of the `workflows` directory).

I'm not sure what effect that would have for users that don't sync their workflows and have everything in the default directory. I don't know exactly what the default location is.
