### ISSUE TITLE
Add mechanism to prevent update to Alfred-3-only workflows under Alfred 2

### ISSUE THREAD

**Issue by deanishe** [deanishe/alfred-workflow#84]
There needs to be some way to mark updates as being incompatible with Alfred 2. There's no obvious (to me) way to do that at the supply (GitHub) end. You'd probably either have to create a separate repo or follow a convention like using `-a3-` in the filename of every future release of a workflow that once supported Alfred 2…

As a result, it's probably best to add an option to Alfred-Workflow's update mechanism that will prevent any further updates if the workflow is running under Alfred 2.

The best solution I can think of is an `alfred2_max_version` option. If your workflow is currently at, say, v1.7.2, you can set `alfred2_max_version` to v1.99 to give yourself plenty of headroom for updates and bugfixes, and bump the version to v2.0 for the first Alfred-3-only release.

Anyone have any suggestions?

**Comment by idpaterson** [comment]
Excellent question. Anyone using semantic versioning for their workflow should certainly consider modifications that only work in Alfred 3 to be a major version update like your example. Unlike Alfred 1 to Alfred 2 the changes may not be as significant so for workflows with enough usage to justify the work, it would be feasible to maintain two major versions for some time until most users have upgraded to Alfred 3, and the max version approach would allow that.

Unfortunately we do not have access to any statistics to determine usage between Alfred 2 and 3 but since it is a paid update for many we can assume the transition of the userbase to Alfred 3 will be neither complete nor especially quick.

The only problem I see with the exclusion approach is that anyone on an older version of alfred-workflow will not have this filter and may still get the 3-only upgrade. The only way I see to address that if a developer were seriously worried about it would be to release binaries with an `.alfred3workflow` extension or similar that would be ignored in older versions of the workflow; however that is not acceptable since they would not work when downloaded directly from GitHub without renaming. 

I would recommend a second possibility since it is likely that some developers will start a new repo for Alfred 3. In addition to the `alfred2_max_version` setting for folks like me who will use the same repo, it would be helpful to support specifying `github_slug` based on the Alfred major version. This would ease the transition for developers who decide to start fresh with a new repository. If the repository was not advertised and put to use for communicating with users the switch really does not affect users. I suspect that will be the case for many workflows. This would give people the ability to retain existing users with a clearer separation between their version 2 and 3 workflow than a major version and would similarly allow concurrent development on both workflows. I would still advocate keeping the same repo unless there are huge changes to your workflow, but I think this option would be put to use by some.

Some considerations:

- How high are the stakes? What happens in Alfred 2 if the workflow is incompatible?
    - An update would cause the workflow to become unusable *without warning*.
    - Hopefully this can be resolved in an Alfred 2 update but currently it's bad news.
    - I created the example workflow in Alfred 2 then pasted some Alfred 3 components and exported again. Then in Alfred 2 I installed the new workflow over the existing working one.
![update](https://cloud.githubusercontent.com/assets/507058/15506554/22f4081e-2196-11e6-83fc-0f2c5625897e.png)
![oops](https://cloud.githubusercontent.com/assets/507058/15506563/291acd4a-2196-11e6-944b-312b0cff1c88.png)
- Has @shawnrice discussed how Packal.org will handle Alfred version compatibility?
    - A workflow file naming scheme would be quite annoying to maintain unless it is consistent across all channels
- Developers will also need to make the distinction obvious on GitHub if a new release only works in Alfred 3
    - A major version update is a good clue but we will also need to be very clear about compatibility in our releases and readme links
   - An entirely separate repository is about as clear as you can get
- Some people might benefit from starting a new repo for Alfred 3
    - This allows each repo to have an accurate and easily accessible README and release history devoted to the respective Alfred version
    - For projects that make heavy use of GitHub for issues, followers, etc, this is not an option

**Comment by deanishe** [comment]
I'm not a big fan of the new-repo route for exactly the reason you mention: I'd hate to lose the stars/followers some of my repos have.

Regarding your compatibility test: Did Alfred 2 overwrite an existing, *working* workflow with an *non-working* Alfred 3 one? Or did you install it some other way?

I definitely take your point about old versions doing an end run around the check. That is far from an ideal solution.

As best I can tell, the only way to make incompatible updates invisible to older versions of the library is with a file extension that isn't `.alfredworkflow` or a release tag that won't parse as semver (e.g. `a3v2.1` or something probably equally gruesome).

I think a different file extension is definitely the cleanest solution. I'll ask Andrew about adding an additional `.alfred3workflow` or `.alfredworkflow3` extension. Future versions of the library would preferentially look for those files in GitHub releases.

**Comment by idpaterson** [comment]
> Regarding your compatibility test: Did Alfred 2 overwrite an existing, working workflow with an non-working Alfred 3 one? Or did you install it some other way?

Yes it did exactly that, for clarity these are the STR:

1. Add the`Should I watch this movie?` example workflow in Alfred 2
2. Export the workflow to `Should I watch this movie 2.alfredworkflow`
3. Install that workflow in Alfred 3; as expected it works just fine
4. Add a component to the same workflow (it does not seem that it even needs to be an Alfred-3-only component; adding a Hotkey exhibits the same behavior)
5. Export the modified workflow to `Should I watch this movie 3.alfredworkflow`
6. Return to Alfred 2; the original Should I watch this movie? workflow should still work properly.
7. Install the modified `Should I watch this movie 3.alfredworkflow`
8. Alfred shows the normal installation prompt and overwrites the old version leaving just an incompatibility message as shown

Excellent idea to contact Andrew, I believe that a file extension for Alfred 3 would be the best way to avoid installs in Alfred 2, both initiated by a workflow and by manual download and install. The file extension also provides a consistent visible indication to the user that a workflow is only for Alfred 3. 

As long as Alfred 2 is still able to install incompatible workflows as shown above these fixes are very important. While older versions should be readily available on GitHub, older versions of workflows distributed solely on Packal or the Alfred forum may not be possible to retrieve. Features that allow users to remain on an old version of Alfred rather than paying for the upgrade may not be high on the priority list, but hopefully this proposal will be well-received.

Additionally, while we have thus far concentrated on cases of disambiguation, I believe that workflows exported from Alfred 3 should automatically be named with this new extension. I fear that based on the test above even a workflow created in Alfred 3 using only Alfred-2-compatible features will still not work in Alfred 2. To me that suggests that the new extension should become the default with—preferably—the original `.alfredworkflow` extension reserved as a guarantee of Alfred 2 compatibility. I still think that Alfred 2 should be updated to not install an incompatible workflow regardless of the file extension, but hopefully we are still early enough into Alfred 3 that the extension should be a cue to the user of Alfred 2 compatibility. This is a similar issue to the file extension change from Alfred 1 to Alfred 2, but in that case compatibility was not maintained.

**Comment by shawnrice** [comment]
Packal does keep all the old versions of the workflows, but I need to build in the compatibility for v2 versus v3, which will take a bit of time. Andrew and I had some conversations about this a while ago, and the solution he preferred was a bit less elegant in terms of separating data, but I have some workarounds. Thankfully, I still have an older computer running Alfred2 to test these on.
I haven't done a full analysis to see the differences in the structure of the info.plist files made between v2 and v3 (excepting a cursory look to see how variables and export instructions are stored).
I'll send more updates when I have new info.

On Wed, May 25, 2016 at 11:08, Ian Paterson <notifications@github.com> wrote:
Regarding your compatibility test: Did Alfred 2 overwrite an existing, working workflow with an non-working Alfred 3 one? Or did you install it some other way?

Yes it did exactly that, for clarity these are the STR:

 1. Add the Should I watch this movie? example workflow in Alfred 2
 2. Export the workflow to Should I watch this movie 2.alfredworkflow
 3. Install that workflow in Alfred 3; as expected it works just fine
 4. Add a component to the same workflow (it does not seem that it even needs to be an Alfred-3-only component; adding a Hotkey exhibits the same behavior)
 5. Export the modified workflow to Should I watch this movie 3.alfredworkflow
 6. Return to Alfred 2; the original Should I watch this movie? workflow should still work properly.
 7. Install the modified Should I watch this movie 3.alfredworkflow
 8. Alfred shows the normal installation prompt and overwrites the old version leaving just an incompatibility message as shown

Excellent idea to contact Andrew, I believe that a file extension for Alfred 3 would be the best way to avoid installs in Alfred 2, both initiated by a workflow and by manual download and install. The file extension also provides a consistent visible indication to the user that a workflow is only for Alfred 3.

As long as Alfred 2 is still able to install incompatible workflows as shown above these fixes are very important. While older versions should be readily available on GitHub, older versions of workflows distributed solely on Packal or the Alfred forum may not be possible to retrieve. Features that allow users to remain on an old version of Alfred rather than paying for the upgrade may not be high on the priority list, but hopefully this proposal will be well-received.

Additionally, while we have thus far concentrated on cases of disambiguation, I believe that workflows exported from Alfred 3 should automatically be named with this new extension. I fear that based on the test above even a workflow created in Alfred 3 using only Alfred-2-compatible features will still not work in Alfred 2. To me that suggests that the new extension should become the default with—preferably—the original .alfredworkflow extension reserved as a guarantee of Alfred 2 compatibility. I still think that Alfred 2 should be updated to not install an incompatible workflow regardless of the file extension, but hopefully we are still early enough into Alfred 3 that the extension should be a cue to the user of Alfred 2 compatibility. This is a similar issue to the file extension change from Alfred 1 to Alfred 2, but in that case compatibility was not maintained.

**Comment by deanishe** [comment]
This slipped my mind there. I've [posted a thread on the forum](http://www.alfredforum.com/topic/9024-alternative-file-extension-for-alfred-3-only-workflows/) rather than contact Andrew directly. Hopefully, other developers will weigh in, too 😉

**Comment by idpaterson** [comment]
Thanks, I will contribute there as well.

**Comment by idpaterson** [comment]
In light of [Andrew's response](http://www.alfredforum.com/topic/9024-alternative-file-extension-for-alfred-3-only-workflows/?p=45004)
> It's unlikely that i'll be changing the workflow extension for Alfred 3, but I can add a field into the info.plist to say which Alfred version the workflow was exported from

would it be possible to inspect the workflow after the user has chosen to download the update (based only on the Alfred version flag in info.plist) and record the release as incompatible so that it does not prompt again? That is not ideal and may not be worth dealing with a dependency to unzip the .alfredworkflow file. 

Assuming there will be no extension change reduces the possibilities here and makes it more difficult to think about an approach that would be worth the effort, easy for developers, and not break direct-from-github downloads.

**Comment by deanishe** [comment]
Theoretically, we can add any features we want to the library going forward. The chief difficulty still lies in stopping old workflows trying to commit suicide, and it appears the only way to do that is to mangle the GH release.

How about adding both mangling options?

Add `alfred3_tag_prefix` and `alfred3_extension` to `update_settings`, and let authors decide whether to used fucked up version numbers or fucked up file extensions.

**Comment by vitorgalvao** [comment]
@deanishe Might’ve missed the [latest reply](http://www.alfredforum.com/topic/9024-alternative-file-extension-for-alfred-3-only-workflows/#entry45014), but:

> I tell you what, I'll make it so Alfred also recognises alfred3workflow the same as alfredworkflow in 3.0.2... but exporting from Alfred 3 I'd like to keep as always .alfredworkflow

Sounds acceptable. It’s adding the new extension and not making it the default.

**Comment by deanishe** [comment]
Thanks, @vitorgalvao. That answers that question, then.

So, going forward, the update mechanism should: First, check major version of Alfred. If it's 3, then preferentially look for `.alfred3workflow` files in releases, falling back to `.alfredworkflow`. Under Alfred 2, only look for `.alfredworkflow` files. As now, multiple workflow files of the same type in a single release invalidate the release.

How does that sound?

**Comment by idpaterson** [comment]
Sounds good to me, if you add options to update_settings is there any value in generalizing the settings structure to allow for future versions of Alfred, just in case? like `'alfred_compatibility': { '3': { 'tag_prefix': 'alfred-3-' }, '4': { 'tag_prefix': 'alfred-4-' } }`.

**Comment by deanishe** [comment]
Not in this branch. v2's update system is going to be based on plugins and hooks (like the rest of it). Haven't figured out the API yet.

I basically got stuck trying to figure out a better serializer API (and everything else left depends on that). I think I'll just say, "fuck it" and port the existing one over.

**Comment by deanishe** [comment]
Added in b87f117b4c46a8df2bdcabde40344262cdcab925

When run under Alfred 3, AW will prefer `.alfred3workflow` files in releases.
