### ISSUE TITLE
Questions regarding the effect on workflow execution speed of this workflow helper

### ISSUE THREAD

**Issue by Jyqft** [deanishe/alfred-workflow#91]
1. What is the effect of this workflow helper on the execution speed of a given workflow? I understand that the workflow helper makes writing workflows from scratch easier because of its built-in tools like fuzzy filtering and error displaying... but what if raw execution speed is the only concern?
2. For this workflow helper, will switching the output from XML to JSON increase execution speed of a given workflow? Although, I understand that one con for doing this is leaving Alfred 2 users in the dust.

**Comment by idpaterson** [comment]
Just speaking from personal experience, I've found alfred-workflow to be one of the fastest workflow helpers available. Awhile ago when I switched my workflow away from AppleScript (a public API became available so it was no longer necessary to interact with a desktop app) I tried all of the workflow helpers that I could find to determine which was the best balance between speed and functionality.

Alfred-Workflow was certainly the fastest for Python. PHP was faster but I find PHP unpalatable and the many additional features of Alfred-Workflow were intriguing. There were two primary factors that affected what "fast" means. First, the time required for the interpreter to load for a basic Hello World script. For AppleScript this was something like 700-900ms while PHP and Python were less than 50ms. Second, the number of libraries imported. It is best to import as-needed to avoid a huge dependency tree that causes everything you could possibly need to be loaded on every invocation. Switching the output format would probably have a negligible impact on the speed since in my experience loading the interpreter and dependencies are the majority timesinks outside of your custom workflow logic.

My workflow uses a single script filter for everything, it just loops back on itself with autocompletes then triggers a script action. It is not as fast as I would like it to be but it is fast enough (100-200ms which includes some natural language processing). Some of the routing logic could be done in Alfred 3 but I value Alfred 2 compatibility. Alfred 3 greatly expands what you can do in a workflow without any helper, so it depends what you're trying to accomplish.

I found the following tricks to be beneficial for creating efficient script filters in Alfred:

1. If every keystroke fires off or enqueues a script be sure to terminate the previous script rather than enqueueing it (*Run Behavior* setting). When the user stops typing you want to show results based on what they actually typed, not based on 10 characters ago. 
2. Use bash to run your script filter since it can run immediately without firing up an interpreter. In your bash script, write the current full Alfred query to a file, e.g. `echo "{query}" > .query` before launching python. This file will always represent the most recent Alfred query even if your python script is terminated due to another keypress. This is very important if you use text from the query when a script is actioned (in my case, adding a task to a task manager app). It is not acceptable to action text that is missing a few characters but when the user presses return the `arg` in the last-generated script filter response may still be a few keystrokes behind. Load the `.query` file in the script that handles the action rather than trusting `{query}` when performing actions based on user input to guarantee that you handle the complete query.
3. Make your main script very lean; anything that is imported can be compiled to byte code for faster interpretation.

Of the features provided by Alfred-Workflow I most value:

1. Built-in automatic updates from GitHub - great user experience and a reasonable assurance that your users will be on the latest version. I don't think you will find this is any other workflow helper
2. The simplification of responding to Alfred without touching XML
3. The simplification of dealing with workflow cache, data files, and the keychain
4. Test coverage and documentation – it works as-documented, and it keeps working when you update it

**Comment by deanishe** [comment]
Alfred-Workflow is built with half an eye to performance. It's pretty lightweight (the vast majority of the "code" is comments) and almost everything is loaded lazily only when needed.

`Workflow.filter()` is slow and tops out at a few hundred items. With larger datasets, use `sqlite` or let Alfred do the filtering.

> but what if raw execution speed is the only concern?

Don't use an interpreted language.

Bottom line: If you have real concerns with Alfred-Workflow's performance, Python—or any interpreted language—probably isn't the right tool for the job. You're not going to get a whole lot more done in the twentieth of a second or so you'd save by not using AW.

You get performance by building your workflow in a smart way. Use intelligent Run Behaviour settings and lightweight Script Filter scripts, like @idpaterson said above. If you can't "architect" your way to good performance with smart use of Alfred, lazy importing and loading, caching, background processes, and `sqlite` or the like, then you need to look at a faster language.

**Comment by deanishe** [comment]
> Switching the output format would probably have a negligible impact on the speed

The underlying XML and JSON libraries are both written in C, IIRC, so reducing the number of items you output or caching the XML/JSON is where the gains are at.

BTW, @idpaterson, have you tried/looked at the new [`Workflow3`](http://www.deanishe.net/alfred-workflow/api/workflow3.html#module-workflow3) class, especially [workflow variables](http://www.deanishe.net/alfred-workflow/user-manual/workflow-variables.html)? I'm keen for feedback.

**Comment by idpaterson** [comment]
@deanishe I am eager to check out the work you've been doing but have not had the time recently to do any experimentation. I have been watching and wanted to provide some feedback on #85 but didn't have enough insight to comment constructively. I only have the one workflow and haven't taken a serious look at the new Alfred 3 goodies since it will be some time still before I switch. After a quick look I'm excited to see that modifiers can have distinct validity and variables, I definitely have a few use cases for that. I'll post on #85 when I have more time to review.

**Comment by Jyqft** [comment]
Thanks, I learned a lot.

@idpaterson said:
> Use bash to run your script filter since it can run immediately without firing up an interpreter. In your bash script, write the current full Alfred query to a file, e.g. echo "{query}" > .query before launching python.

I actually have a workflow written using this workflow helper, wherein the title of the script filter output is based on the query. It is as you say—if you type and action it fast, some of the characters from the latter part of the query get chopped off. I currently invoke the script filter using bash and doing this:

    python my_script.py "{query}"

I also tried doing your suggestion like this:

    echo "{query}" > .query
    python go_to_reddit_subreddit.py "$(< .query)"

but they're just the same in terms of execution speed. Am I doing it right?

**Comment by idpaterson** [comment]
Here's the trick, let's look at the full sequence of events in a script filter. For this example I'm going to type "test" pausing enough to generate some output then immediately press return to action the result.

1. type 't', Alfred runs the script filter which gets the input "t"
2. type 'e', Alfred terminates the previous execution and runs the script filter again which gets the input "te"
3. Wait a moment for the output of "te" to be generated. The script filter returns an actionable result to Alfred that includes `arg="te", valid=True`
4. type 's', Alfred runs the script filter which gets the input "tes" and leaves the previous output
5. type 't', Alfred terminates the previous execution and runs the script filter which gets the input "test" and leaves the previous output
6. Press return immediately before the response for "test." You've just actioned "te" because it was the `arg` for the first valid item 

As you know, that is the problem and the reason we see a truncated result. Here's where the arbitrarily-named `.query` file comes in.

7. When the item is actioned, Alfred will pass the arg to the next action in your workflow. Let's say it is a script action that calls another Python script. In my case it is the same script that handles the script filter so that I can leverage the same routing logic, just with a `--commit` param to signify that the corresponding action should be performed.
8. If you pass this script action `{query}`, it will get "te" but if you give it `$(< .query)` it will get "test" - this is the point to use that `.query` file. 

I think my workflow uses `arg="--cached-query"` or something for cases where the .query file should be used instead of the interpolated `{query}` then loads the `.query` file in Python. This may or may not be something you want to do in all cases, but it works very well when you're performing actions on text collected from a script filter.

I don't think that loading the `.query` file in the script filter will have any effect if you set up the script filter to terminate processes on each keystroke. It would always be the same as `{query}` in that case. This is really just for the next step in the chain. If the next step in Alfred is something where you can't do any processing like a notification you could just put an intermediary script in there to `cat .query && rm .query` so that the next step gets the full text as `{query}`.

**Comment by deanishe** [comment]
> I have been watching and wanted to provide some feedback on #85 but didn't have enough insight to comment constructively.

No hurry. I figure it'll be several months and several workflows before anyone has a clear idea of what would work best. I've gone with a compromise solution for the time being.

> After a quick look I'm excited to see that modifiers can have distinct validity and variables

[My idea](http://www.alfredforum.com/topic/5031-can-a-script-filter-result-be-valid-only-for-certain-modifiers/?p=30764)! I'm actually a bit disappointed you can't change the icon. That'd provide far better feedback than changing the subtitle, especially as users can turn subtitles off. Hopefully, that's coming in an Alfred update.

Variables are certainly very handy for control flow in Alfred. I tend to write my workflows as command-line programs, and something I've been trying recently is libraries like [Click](http://click.pocoo.org/) that can auto-map environment variables to command-line options.

Say you have a Script Filter connected to a Run Script that reads `./prog "$1"`. If you set `PROG_DEBUG=1` and `PROG_BROWSER=chrome` in your Script Filter output variables, your Run Script is then equivalent to `./prog --debug --browser=chrome "$1"`. *Very* handy.

**Comment by Jyqft** [comment]
@idpaterson:
That's the thing—as I said before, I tried using both the Alfred {query} variable and reading it after writing it to a file, but both seem to yield the same results. Do you have a sample workflow that makes use of the latter method? I'm afraid I didn't understand the entirety of your latest post.

@deanishe:
The reason I ask is because using the Alfred Workflow workflow helper seems to make things load slower—slow enough to be noticeable in normal usage.

Take these two Python scripts as an example. You'll find that printing using Python's JSON module (I'm using Alfred 3—but based on what you said, it doesn't matter if it's JSON or XML) is faster than printing using this workflow helper. This is understandable because the workflow helper is probably loading other things. But, the difference between the two is very noticeable during regular use.

**print_using_alfredworkflow.py**
```
#!/usr/bin/python
# encoding: UTF-8

import sys
from workflow import Workflow

def main(wf):
 
	# Choose directory...
	wf.add_item(title = "Choose directory...",
			arg = "<chooseDir>",
			valid = True,
			icontype = "filetype",
			icon = "public.folder")
		 
	# Send output to Alfred
	wf.send_feedback()
	 
if __name__ == '__main__':
	wf = Workflow()
	sys.exit(wf.run(main))
```

**print_using_pythonjson.py**
```
#!/usr/bin/python
#encoding: UTF-8

import sys
import json

def main(argv):

	dirs_json = []

	# Choose directory...
	dirs_json += [
	{
		"title": "Choose directory...",
		"arg": "<chooseDir>",
		"icon": {
			"type": "filetype",
			"path": "public.folder"
		}
	}
	]

	# Print JSON output
	main_json = {"items": dirs_json}
	print json.dumps(main_json, indent = 4)
	
if __name__ == "__main__":
	main(sys.argv)
```

**Comment by deanishe** [comment]
Sure, it's noticeably slower in a script that does almost nothing. If you're just dumping a static list to Alfred, you don't even need Python. Use `cat` or a List Filter.

**Comment by idpaterson** [comment]
Please provide the timing that you're seeing for comparison, e.g. `time python print_using_pythonjson.py "some query"`. You might also consider checking the timing after each statement to see what takes longest (e.g. after the import, after the constructor, after sending feedback).

I made the choice to trade a bit of performance for a lot of convenience and functionality. If you're not using the convenience features of Alfred-Workflow (e.g. cache/storage file paths, keychain, automatic updates) then by all means talk directly to Alfred. It's even easier to do now that JSON is supported.

You're not going to get any general guidelines on where to draw the line between components of a workflow that require a workflow helper and those that do not. It depends on many factors – speed requirement, Alfred-Workflow features needed, the amount of work you want to do, your willingness to reinvent the wheel, and the intended user experience. Use it wherever it makes sense for your specific workflow.

Regarding the `.query` file again, my workflow has a script filter that handles all of the "user interface" of the workflow and a script action that is called when the user actions something. The script filter writes the `.query` file and the script action reads it. Introduce obvious latency in your script filter like `time.sleep(5)` to easily test the missing characters scenario.

![script filter and action](https://cloud.githubusercontent.com/assets/507058/16531246/949b3bd8-3f99-11e6-81d3-5ae9b80a19d8.png)

### Script filter:
```bash
echo "{query}" > .query
/usr/bin/env python -O alfred-wunderlist-workflow.py "{query}"
```

### Script action:
```bash
/usr/bin/env python -O alfred-wunderlist-workflow.py "{query}" --commit
```

As mentioned in the previous comment, the script filter may respond with `--stored-query` rather than what the user typed. This is where I use the `.query` file to guarantee that the input represents the user's complete query.

```python
	# Read the stored query, which will correspond to the user's alfred query
	# as of the very latest keystroke. This may be different than the query
	# when this script was launched due to the startup latency.
	if command == '--stored-query':
		query_file = workflow().workflowfile('.query')
		with open(query_file, 'r') as f:
			command = workflow().decode(f.read())
		os.remove(query_file)
```
